HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 1s [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 2s [Retry 2/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 4s [Retry 3/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 8s [Retry 4/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 8s [Retry 5/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 1s [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 2s [Retry 2/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 4s [Retry 3/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 8s [Retry 4/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 8s [Retry 5/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Using the latest cached version of the dataset since flwrlabs/pacs couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /home/apiasecz/.cache/huggingface/datasets/flwrlabs___pacs/default/0.0.0/394113073258ead631f617d2e13bb377c0715c4b (last modified on Wed Jan 29 16:59:35 2025).
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 1s [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 2s [Retry 2/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 4s [Retry 3/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 8s [Retry 4/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 8s [Retry 5/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 1s [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 2s [Retry 2/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 4s [Retry 3/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 8s [Retry 4/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 8s [Retry 5/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Using the latest cached version of the dataset since flwrlabs/pacs couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /home/apiasecz/.cache/huggingface/datasets/flwrlabs___pacs/default/0.0.0/394113073258ead631f617d2e13bb377c0715c4b (last modified on Wed Jan 29 16:59:35 2025).
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 1s [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 2s [Retry 2/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 4s [Retry 3/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 8s [Retry 4/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
Retrying in 8s [Retry 5/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/main/README.md
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 1s [Retry 1/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 2s [Retry 2/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 4s [Retry 3/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 8s [Retry 4/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Retrying in 8s [Retry 5/5].
HTTP Error 429 thrown while requesting HEAD https://huggingface.co/datasets/flwrlabs/pacs/resolve/394113073258ead631f617d2e13bb377c0715c4b/pacs.py
Using the latest cached version of the dataset since flwrlabs/pacs couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /home/apiasecz/.cache/huggingface/datasets/flwrlabs___pacs/default/0.0.0/394113073258ead631f617d2e13bb377c0715c4b (last modified on Wed Jan 29 16:59:35 2025).
Device: cuda
CUDA Version: 12.1
cuDNN Version: 8902
PyTorch Version: 2.3.0

Model used: PACSCNN
Initial dataset creation
Initial dataset creation
Initial loss: 5.803514003753662
<__main__.Policy object at 0x149c785711c0>
5.803514003753662
Loss historical diff: 0.0; Loss Difference: 0.0, Decision: 0
Round 1 took 5.301429033279419s, results:
{'t': 0, 'current_accuracy': 0.30859375, 'current_loss': 5.7629945278167725, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['cartoon']}
Loss historical diff: 0.0; Loss Difference: 0.0, Decision: 0
Round 2 took 4.9856719970703125s, results:
{'t': 1, 'current_accuracy': 0.30859375, 'current_loss': 5.7629945278167725, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['cartoon']}
Loss historical diff: 2.384185791015625e-07; Loss Difference: 0.0, Decision: 0
Round 3 took 4.48558235168457s, results:
{'t': 2, 'current_accuracy': 0.30859375, 'current_loss': 5.762994766235352, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['cartoon']}
Loss historical diff: 0.0; Loss Difference: 0.0, Decision: 0
Round 4 took 4.253526926040649s, results:
{'t': 3, 'current_accuracy': 0.30859375, 'current_loss': 5.7629945278167725, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['cartoon']}
Loss historical diff: 7.152557373046875e-07; Loss Difference: 0.0, Decision: 0
Round 5 took 5.089220285415649s, results:
{'t': 4, 'current_accuracy': 0.30859375, 'current_loss': 5.76299524307251, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['cartoon']}
Loss historical diff: 4.76837158203125e-07; Loss Difference: 0.0, Decision: 0
Round 6 took 4.558403253555298s, results:
{'t': 5, 'current_accuracy': 0.30859375, 'current_loss': 5.762995004653931, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['cartoon']}
Loss historical diff: 2.384185791015625e-07; Loss Difference: 0.0, Decision: 0
Round 7 took 4.846914768218994s, results:
{'t': 6, 'current_accuracy': 0.30859375, 'current_loss': 5.762994766235352, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['cartoon']}
Loss historical diff: 2.384185791015625e-07; Loss Difference: 0.0, Decision: 0
Round 8 took 4.9551379680633545s, results:
{'t': 7, 'current_accuracy': 0.30859375, 'current_loss': 5.762994766235352, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['cartoon']}
Loss historical diff: 2.384185791015625e-07; Loss Difference: 0.0, Decision: 0
Round 9 took 5.060129642486572s, results:
{'t': 8, 'current_accuracy': 0.30859375, 'current_loss': 5.762994766235352, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['cartoon']}
Loss historical diff: 0.0; Loss Difference: 0.0, Decision: 0
Round 10 took 4.802959203720093s, results:
{'t': 9, 'current_accuracy': 0.30859375, 'current_loss': 5.762993812561035, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['cartoon']}
Loss historical diff: 0.0; Loss Difference: 0.0, Decision: 0
Round 11 took 4.476746082305908s, results:
{'t': 10, 'current_accuracy': 0.30859375, 'current_loss': 5.762993812561035, 'train_loss': None, 'decision': 0, 'drift_rate': 0.001, 'target_domains': ['photo']}
Loss historical diff: 7.152557373046875e-07; Loss Difference: 0.0, Decision: 0
Round 12 took 4.770570278167725s, results:
{'t': 11, 'current_accuracy': 0.30859375, 'current_loss': 5.7629945278167725, 'train_loss': None, 'decision': 0, 'drift_rate': 0.001670010459667194, 'target_domains': ['sketch']}
Loss historical diff: 1.1920928955078125e-06; Loss Difference: 0.0, Decision: 0
Round 13 took 4.821262836456299s, results:
{'t': 12, 'current_accuracy': 0.30859375, 'current_loss': 5.762995004653931, 'train_loss': None, 'decision': 0, 'drift_rate': 0.002338845493317048, 'target_domains': ['sketch']}
Loss historical diff: 4.76837158203125e-07; Loss Difference: 0.0, Decision: 0
Round 14 took 4.895885705947876s, results:
{'t': 13, 'current_accuracy': 0.30859375, 'current_loss': 5.762994289398193, 'train_loss': None, 'decision': 0, 'drift_rate': 0.003005331737028868, 'target_domains': ['sketch']}
Loss historical diff: 9.5367431640625e-07; Loss Difference: 0.0, Decision: 0
Round 15 took 4.535869598388672s, results:
{'t': 14, 'current_accuracy': 0.30859375, 'current_loss': 5.762994766235352, 'train_loss': None, 'decision': 0, 'drift_rate': 0.003668299947457636, 'target_domains': ['sketch']}
Loss historical diff: 0.026726484298706055; Loss Difference: 0.0, Decision: 0
Round 16 took 3.938605308532715s, results:
{'t': 15, 'current_accuracy': 0.3046875, 'current_loss': 5.789720296859741, 'train_loss': None, 'decision': 0, 'drift_rate': 0.00432658705308415, 'target_domains': ['sketch']}
Loss historical diff: 0.06856703758239746; Loss Difference: 0.0, Decision: 1
/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with an OutOfMemoryError: CUDA out of memory. Tried to allocate 1.00 GiB. GPU  (Triggered internally at /opt/conda/conda-bld/pytorch_1712608847532/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:924.)
  return F.conv2d(input, weight, bias, self.stride,
/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with an OutOfMemoryError: CUDA out of memory. Tried to allocate 514.00 MiB. GPU  (Triggered internally at /opt/conda/conda-bld/pytorch_1712608847532/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:924.)
  return F.conv2d(input, weight, bias, self.stride,
/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with an OutOfMemoryError: CUDA out of memory. Tried to allocate 2.25 GiB. GPU  (Triggered internally at /opt/conda/conda-bld/pytorch_1712608847532/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:924.)
  return F.conv2d(input, weight, bias, self.stride,
Traceback (most recent call last):
  File "/home/apiasecz/programming/concept_drift_optimal_adaptation_FL/src/execute/evaluate_policy.py", line 753, in <module>
    main()
  File "/home/apiasecz/programming/concept_drift_optimal_adaptation_FL/src/execute/evaluate_policy.py", line 733, in main
    evaluate_policy_under_drift(
  File "/home/apiasecz/programming/concept_drift_optimal_adaptation_FL/src/execute/evaluate_policy.py", line 554, in evaluate_policy_under_drift
    update_loss = agent_train.update_steps(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/programming/Federated_Learning_Base_Toolkit_torch/fl_toolkit/federated/client.py", line 202, in update_steps
    return self.model.update_steps(self.data_loader, optimizer, loss_fn, num_updates, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/programming/Federated_Learning_Base_Toolkit_torch/fl_toolkit/models/base_model.py", line 93, in update_steps
    outputs = self.model(inputs)
              ^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/programming/concept_drift_optimal_adaptation_FL/src/execute/evaluate_policy.py", line 47, in forward
    x = self.features(x)
        ^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/programming/concept_drift_optimal_adaptation_FL/src/execute/evaluate_policy.py", line 70, in forward
    out = self.bn1(out)
          ^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/batchnorm.py", line 175, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/functional.py", line 2509, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB. GPU 
